### ISSUE TITLE
GitHub Actions workflow fails on release

### ISSUE THREAD

**Issue by peterstangl** [wilson-eft/wilson#101]
The shell script that should verify that the release version matches the source code version throws an error and exits due to missing dependencies when importing the version number from `wilson` (`ModuleNotFoundError: No module named 'numpy'`, see https://github.com/wilson-eft/wilson/commit/fd909c354d3c464e1486f2c2ef481e98297c1487/checks/6974469608/logs).

@dvandyk, @jasonaebischerGIT, @klieret, @DavidMStraub could please one of you upload the new release to PyPI again?

**Comment by peterstangl** [comment]
The issue has been fixed in PR #102 and I was able to upload the new version to PyPI by re-publishing the release.

**Comment by dvandyk** [comment]
Oh boy, sorry for that. While the workflow is hard to test, this I should have noticed.
