### ISSUE TITLE
`loop` argument not forwarded to `alpha_s` in `m_{b|c|s}`

### ISSUE THREAD

**Issue by Element-126** [wilson-eft/wilson#23]
The `loop` kwarg in `m_b`, `m_c` and `m_s` from the `wilson.util.qcd` module is not forwarded to `alpha_s`, resulting in the default value `loop=3` always being used to evaluate the strong coupling constant.

This leads to a small discrepancy with respect to the Mathematica version of RunDec.

The tests in `wilson.util.test_qcd` currently only cover the default (`loop=3`) case.

Not sure if this is actually an issue, since the difference is small and the docstring explicitly specifies "3-loop computation", but it surprised me a bit so I prefer to report it just in case. Feel free to close if this is intended :-)

https://github.com/wilson-eft/wilson/blob/131f2730f7fe5490da825288f254904cb11fe703/wilson/util/qcd.py#L20

#### `m_b`
https://github.com/wilson-eft/wilson/blob/131f2730f7fe5490da825288f254904cb11fe703/wilson/util/qcd.py#L58
https://github.com/wilson-eft/wilson/blob/131f2730f7fe5490da825288f254904cb11fe703/wilson/util/qcd.py#L64

https://github.com/wilson-eft/wilson/blob/131f2730f7fe5490da825288f254904cb11fe703/wilson/util/qcd.py#L67

https://github.com/wilson-eft/wilson/blob/131f2730f7fe5490da825288f254904cb11fe703/wilson/util/qcd.py#L83

#### `m_c`
https://github.com/wilson-eft/wilson/blob/131f2730f7fe5490da825288f254904cb11fe703/wilson/util/qcd.py#L95
https://github.com/wilson-eft/wilson/blob/131f2730f7fe5490da825288f254904cb11fe703/wilson/util/qcd.py#L102

https://github.com/wilson-eft/wilson/blob/131f2730f7fe5490da825288f254904cb11fe703/wilson/util/qcd.py#L104

#### `m_s`
https://github.com/wilson-eft/wilson/blob/131f2730f7fe5490da825288f254904cb11fe703/wilson/util/qcd.py#L121
https://github.com/wilson-eft/wilson/blob/131f2730f7fe5490da825288f254904cb11fe703/wilson/util/qcd.py#L128

https://github.com/wilson-eft/wilson/blob/131f2730f7fe5490da825288f254904cb11fe703/wilson/util/qcd.py#L130

https://github.com/wilson-eft/wilson/blob/131f2730f7fe5490da825288f254904cb11fe703/wilson/util/qcd.py#L146

Also, small typo:
https://github.com/wilson-eft/wilson/blob/131f2730f7fe5490da825288f254904cb11fe703/wilson/util/qcd.py#L21

**Comment by DavidMStraub** [comment]
Hi, you are right and this is in fact not intentional.

**Comment by Element-126** [comment]
Okay, I will prepare a PR then. How can I run the test suite locally?

**Comment by DavidMStraub** [comment]
Great. I was planning to release version 1.5 later today, do you think you can make it for that?

To run the tests, you need the `nose` package, then you can just run `nostests` in the source directory. (For development I would suggest to install the cloned repository in development mode with `pip3 install -e . --user`).

**Comment by Element-126** [comment]
Yes, I can surely make it. I already fixed the code, so I just need to write new tests with `loop != 3`. I am using `nose` as well, so there should be no technical difficulties here.

**Comment by Element-126** [comment]
There are still two failing tests, which give a slightly different answer from the Mathematica version. This might be an issue with my validation code. Hopefully I will figure it out today.

Partial progress here (do not merge yet): https://github.com/Element-126/wilson/tree/fix-23

**Comment by Element-126** [comment]
I have found what is causing the failures, but I am still not sure what is the proper way to fix it.
I'll read the relevant part of the RunDec paper again and this will hopefully clarify everything.
