### ISSUE TITLE
Translation of bases does not work properly with "match_run" .

### ISSUE THREAD

**Issue by jackypheno** [wilson-eft/wilson#31]
# Take simple example: 

wc_dict = {'qd1_1211':1e-6}

# Instantiate Wilson with eft='SMEFT'  and basis='Warsaw'
wc_in = Wilson(wc_dict, 1e3, 'SMEFT', 'Warsaw')

# Use the 'match_run' to translate the wilson coefficients to 'Warsaw up' basis keeping the output scale same :
wc_out = wc_in.match_run(1e3, 'SMEFT', 'Warsaw up')
print(wc_out)

The output is:

## WCxf Wilson coefficients

**EFT:** `SMEFT`

**Basis:** `Warsaw`

**Scale:** 1000.0 GeV

### Values

| WC name | Value |
|--------------------|----------------------------------------------------|
| `qd1_1211` | 1e-06 |

The basis is still 'Warsaw' !  Note: the gauge and yukawa couplings are set to zero to avoid any effect due to running.

**Comment by jackypheno** [comment]
My guess is 

https://github.com/wilson-eft/wilson/blob/fb2cf94aab283edd1868500b4bf22e8d24c69d07/wilson/classes.py#L197

should be replaced by

`wc_out = smeft.run(scale, accuracy=smeft_accuracy).translate(basis)`

**Comment by DavidMStraub** [comment]
Thanks Jacky, and you are right about the solution! Do you want to fix it in a PR? It might also make sense to add your minimal example above as a unit test.

**Comment by jackypheno** [comment]
Hi David, 
I created a pull request to fix it. Yes it's a good idea to add the unittest. I will do it.

**Comment by DavidMStraub** [comment]
Fixed by #32.
