### ISSUE TITLE
Does not match with the formula (A.55) in arxiv:1310.4838

### ISSUE THREAD

**Issue by haolinli1991** [wilson-eft/wilson#46]
https://github.com/wilson-eft/wilson/blob/65ee5f39895bb3d65d3a1deb8e3303733702a6d8/wilson/run/smeft/beta.py#L1649

The line 1649 and line 1651 in beta.py seem to have the reversed factors of gammaq and gammad compared with the 3rd last and the last terms in formula  A.55 in arxiv: 1301.4838

Do you have any idea which one is correct?

Best,
Haolin

**Comment by DavidMStraub** [comment]
> Do you have any idea which one is correct?

Ours.

Actually, it agrees if you check the most recent arXiv version.

I pointed out this mistake to the authors.

**Comment by haolinli1991** [comment]
> > Do you have any idea which one is correct?
> 
> Ours.
> 
> Actually, it agrees if you check the most recent arXiv version.
> 
> I pointed out this mistake to the authors.

Great, Thanks very much
