### ISSUE TITLE
Question: How to get direct access beta functions?

### ISSUE THREAD

**Issue by TomSteu** [wilson-eft/wilson#65]
Dear wilson contributors,

I was wondering if there is a straightforward way to directly access the values of SMEFT (and other basis) beta functions?
The reasoning behind this is to test if a set of Wilson coefficients is closed under RG running (without checking all expressions by hand).
For such a test it would suffice to give the relevant WCs some value (e.g. 1) while setting the rest to zero, e.g. define a `Wilson` object. SM parameters also need to be picked, but I imagine the values do not matter a lot (the test does not have to be foolproof).

Cheers,
Tom

**Comment by DavidMStraub** [comment]
The beta functions of all WCs can be evaluated numerically with this function:
https://github.com/wilson-eft/wilson/blob/master/wilson/run/smeft/beta.py#L37

But what's important is that the WCs in the input array are *not* in the WCxf convention, but they are using a symmetrized flavour basis (see appendix A.2 of https://arxiv.org/pdf/1810.07698.pdf for a discussion) following the conventions of DsixTools (this particular module started its life as a Python version of DsixTools' SMEFTRunner, see [here](https://github.com/DsixTools/python-smeftrunner) if you are interested in archaeology).

[This is the method](https://github.com/wilson-eft/wilson/blob/master/wilson/run/smeft/classes.py#L43-L78) that converts the WCxf WCs to the symmetrized basis.

**Comment by TomSteu** [comment]
Very good, this worked out! 
I did end up using the `get_smpar=True` keyword in `SMEFT`, which means the WCs had to be chosen smaller than I anticipated in my initial comment. But in the end, the coefficients switched on by the running could be read-off nevertheless.
