### ISSUE TITLE
New version of wilson on PyPI not working

### ISSUE THREAD

**Issue by peterstangl** [wilson-eft/wilson#67]
@jasonaebischerGIT unfortunately the new version of `wilson` released today on PyPI is not working. The problem seems to be a missing `wcxf-bases` subrepository from https://github.com/wcxf/wcxf-bases that should be contained in the `wilson/wcxf/bases/` folder.

Apart from that, the new version number on PyPI (2.0.1) does not match the latest version number on GitHub (2.1).

**Comment by DavidMStraub** [comment]
`_version.py` must be edited to match the version number.

The missing bases are probably due to not cloning with `git clone --recursive` (although in that case unit tests will fail as well).

**Comment by jasonaebischerGIT** [comment]
The version number is now changed.
And I guess `git clone --recursive` also did the trick.

**Comment by peterstangl** [comment]
Great, thanks @jasonaebischerGIT! I can confirm that the problem is solved (the Travis checks in flavio are working again) :grinning:
