### ISSUE TITLE
Question: Matching SMEFT and WET at one loop

### ISSUE THREAD

**Issue by Stefan-Bissmann** [wilson-eft/wilson#68]
Dear all,
we currently want to use wilson to test our results from our implementation of the matching between SMEFT and WET (especially the flavio basis). However, I ran into some issues and would like to ask whether it is just me not understanding how to use wilson correctly.
So, the example is the following:  Say that we want to match 'CuG_33' to 'C8_bs' and as a cross check to 'CdG_23' (in the basis JMS)
The commands I use are: 

```import wilson 

w = wilson.Wilson({'uG_33': 1e-6}, 80.3, 'SMEFT', 'Warsaw')
w.set_option('smeft_matchingscale', 80.3)
w.set_option('smeft_matching_order', 1)
wc = w.match_run(80.3, 'WET', 'flavio')
print(wc['C8_bs'])
wc2 = w.match_run(80.3, 'WET', 'JMS')
print(wc2['dG_23']) 
```

now, taking conversion factors (vT**2 * 8 * pi**2 /(g3 * mb) * 1 / ( Vtb * Vts)) between flavio and JMS basis into account, the results differ by a factor of 10:

C8_bs = -0.028...
CdG_23 = 8.725e-10 (= 0.0029... after conversion)

Furthermore, they are in conflict with results obtained when I directly use the corresponding code in 'smeft_loop.py', which agrees with our implementation of the matching in https://arxiv.org/pdf/1512.02830.pdf (after taking the conversion factor into account). This result reads -0.041
Maybe I am just mixing different conventions by mistake or do not use wilson correctly? 

Thank you in advance for your help.

**Comment by DavidMStraub** [comment]
Hint: you can enclose inline code in  \` and display code blocks in \`\`\`python ... \`\`\` to make it more readable.

**Comment by DavidMStraub** [comment]
I agree with your conversion factor but disagree with there being a discrepancy. Can you check your numerics?

**Comment by Stefan-Bissmann** [comment]
Thanks a lot for the fast reply!
So, for you everything is just fine when comparing both bases (the results from wilson)?

**Comment by DavidMStraub** [comment]
I'm too lazy to look up the right values, but using rough values I get:

```python
v=246.22
Vtb=1
Vts=0.04
mb=3
g3 = 1.2
print(wc2['dG_23'] / (-1/v**2*Vtb*Vts/(8*pi**2)*mb*g3))
```

The result is `(-0.029003550946260098+0.000543143668753945j)`.

**Comment by Stefan-Bissmann** [comment]
Ok, then it might just be some issue with my numerics. Just wanted to check that I did not mess up anything.
Thank you so much for the fast help! It is much appreciated.
