### ISSUE TITLE
Redundant operators

### ISSUE THREAD

**Issue by jackypheno** [wilson-eft/wilson#72]
I think, since the Wilson coefficient ll_ijji and ll_iijj are related through Fierz, one of them should be removed from the Warsaw basis:

https://github.com/wcxf/wcxf-bases/blob/429bcbf1f2b9fc80f488ffd88b5e497f7dd4a3e2/smeft.warsaw.basis.yml

**Comment by jasonaebischerGIT** [comment]
Yes, I agree. Thanks for bringing it up!

**Comment by DavidMStraub** [comment]
But if you Fierz them, you'll have different SU(2) contractions.

**Comment by DavidMStraub** [comment]
Note: the number of real parameters in this basis has been checked to be 2499. So if there are redundant operators, also https://arxiv.org/pdf/1312.2014.pdf is wrong.

**Comment by jasonaebischerGIT** [comment]
Yes, David is right; Say we compare ll_1122 and ll_1221 (dropping gamma matrices for simplicity):

1122:
(nu_e nu_e)[(nu_mu nu_mu) + (mu mu)] + (e e)[(nu_mu nu_mu) + (mu mu)] 

1221:
(nu_e nu_mu)[(nu_mu nu_e) + (mu e)] + (e mu)[(nu_mu nu_e) + (mu e)]

One can never bring one in the form of the other using Fierz relations.

**Comment by jackypheno** [comment]
@DavidMStraub @jasonaebischerGIT Indeed, thanks for the clarification. Closing.

**Comment by DavidMStraub** [comment]
Glad I could help :slightly_smiling_face:
