### ISSUE TITLE
Github Workflow

### ISSUE THREAD

**Issue by dvandyk** [wilson-eft/wilson#79]
- [x] use ``pypa/gh-action-pypi-publish`` instead of manual upload via twine
 - [x] use PyPI access token
 - [x] check that the tag correspond to the version number recorded in the source code (suggest by @klieret)

**Comment by klieret** [comment]
Also fix #80

**Comment by klieret** [comment]
I actually also think that we should at least test different python3 versions. It's easy to start using some py3.7 feature that isn't in 3.6 etc.
