### ISSUE TITLE
Add PyPI maintainers/owners

### ISSUE THREAD

**Issue by dvandyk** [wilson-eft/wilson#81]
Dear @DavidMStraub,

@jasonaebischerGIT is not listed a owner of the wilson project on PyPI, i.e., he has now means to add further maintainers. Could you add any or all of

  - ``jaebischer``
  - ``klieret``
  - ``peterstangl``
  - ``dvandyk``

Cheers
Danny

**Comment by DavidMStraub** [comment]
Jason promoted to owner.
