### ISSUE TITLE
The value of CKM matrix

### ISSUE THREAD

**Issue by haolinli1991** [wilson-eft/wilson#83]
As far as I understand, when iteratively determine the SM parameters at the High scale (the scale one defined the SMEFT Wilson coefficients), the package uses the value of CKM matrix to fix the value of the Yukawa coupling of fermions at EW scale, which further influences the running of the Wilson coefficients in the SMEFT. 

Assuming the whole iterative programme works, then how do the CKM in this procedure extracted from the experiments? The inclusion of some of the operators for example phi_q3 and phi_ud will indeed change the W boson and quarks interactions, which may alter the global fit of the CKM in those low energy meson decay experiments.  It seems to me that one cannot have a consistent matching between SMEFT and WET without considering running of WET down to the low energy scale to extract the CKM from the low energy flavor observables. 

A naive and consistent way I could think  of to determine the initial value of Yukawa matrices at the high scale is to find their value such that they minimize the chi2 function of the global fit of the relevant low energy observable taking into account all the running and matching effects, but I know this is computationally inapplicable.  So is there any way to analysis the theoretical uncertanties brought by possibly improper value of CKM?

I read a relevant thread https://github.com/wilson-eft/wilson/issues/38, but eager more thought and explanation of this problem.

Thanks,
Haolin

**Comment by DavidMStraub** [comment]
This feature is beyond the scope of wilson, but is actually provided by smelli. @peterstangl

**Comment by peterstangl** [comment]
@haolinli1991, an explanation of the problem and how it is addressed in [smelli](https://github.com/smelli/smelli) can be found in the following slides (starting from page 26): https://indico.in2p3.fr/event/18646/contributions/74406/attachments/54799/71956/straub-lyon-2019.pdf#12

**Comment by peterstangl** [comment]
@DavidMStraub I was wondering already some time ago, if it might be better to implement this treatment of CKM in SMEFT in `wilson` instead of `smelli`. This would e.g. also make it possible to use it directly for the computation of predictions in `flavio`. In this case, `flavio` would just have to take the "NP-dependent CKM elements" from `wilson`. Is there actually some good reason for having this feature not in `wilson` but in `smelli`?

**Comment by DavidMStraub** [comment]
One problem I can think of: it would make Wilson dependent on Flavio, which would create a circular dependency.

**Comment by DavidMStraub** [comment]
It could also be contemplated to merge Wilson, Flavio, and smelli altogether :)

**Comment by haolinli1991** [comment]
> @haolinli1991, an explanation of the problem and how it is addressed in [smelli](https://github.com/smelli/smelli) can be found in the following slides (starting from page 26): https://indico.in2p3.fr/event/18646/contributions/74406/attachments/54799/71956/straub-lyon-2019.pdf#12

Thanks a lot! This should be what I am finding

**Comment by haolinli1991** [comment]
@DavidMStraub @peterstangl , 
Sorry guys I have an additional question to bother you.
Regarding to the matching procedure and the convention in the flavio basis, what was the value of the CKM matrix elements used in the flavio basis in WET? For example, there is a Vud present in the definition of the operator:
![image](https://user-images.githubusercontent.com/31523710/132696994-7f373897-02a5-4a1e-8816-b1d806f4eb96.png)
Is this Vud the one that has been modified by the presence of SMEFT Wilson coefficients or the one obtained by the SM global fit without any new physics effect?

Thanks,
Haolin

**Comment by peterstangl** [comment]
@haolinli1991, sorry for the late reply. The CKM elements that appear in definitions of EFT operators are actually not fixed. If an EFT operator has a prefactor, this means that this prefactor will appear in the expressions that yield the observable predictions. And the parameter values entering this prefactor can be modified by the user.
By default `flavio` uses `flavio.default_parameters`, i.e. it uses the parameters as defined in https://github.com/flav-io/flavio/blob/master/flavio/data/parameters_uncorrelated.yml and https://github.com/flav-io/flavio/blob/master/flavio/data/parameters_correlated.yml.
In `smelli`, by default these input parameters are updated with the CKM elements in the presence of the SMEFT Wilson coefficients.
