### ISSUE TITLE
different options for `smeft_accuracy` result in very different results after running

### ISSUE THREAD

**Issue by Yong-Du** [wilson-eft/wilson#90]
Hi,

I was trying to use the `wilson` package for running some Wilson coefficients from the mZ scale up to 1TeV, but I got very different results (differ by ~1e12) when choosing different options for `smeft_accuracy`. I tried other operators (like `phiD`) as well, but got similar discrepancy. Since I do not expect the RGEs for the Wilson coefficients or the SM parameters to be stiff, I would agree with the methods defined in your `rge.py` file. However, I have a difficulty in understanding this huge discrepancy. Do you have any comments/suggestions? (My code and the output are attached below.)

Thanks,
Yong

Code:
---
```
import wilson as wc
from wilson import Wilson

w = Wilson({'lequ1_1111':1.},
           scale = 91.1876,
           eft = 'SMEFT', basis = 'Warsaw')
w.set_option('smeft_matching_order',1)
w.set_option('smeft_accuracy','leadinglog') 
wc = w.match_run(1000.,'SMEFT','Warsaw') 
print(wc['lequ1_1111'])
w.set_option('smeft_accuracy','integrate') 
wc = w.match_run(1000.,'SMEFT','Warsaw') 
print(wc['lequ1_1111'])
```

The output
---
(0.8122261045241321+3.455055738367379e-09j)
(2.6547291756603105e-12-3.7133250374864686e-14j)

**Comment by DavidMStraub** [comment]
Hi,

I haven't looked at your specific example, but in general this is something that is to be expected if the mixing of Wilson coefficient B into Wilson coefficient A is zero in leading-log approximation. Note also that the numerical value for the Wilson coefficient you are choosing is physically meaningless as 1/GeV² invalidates the EFT expansion.

**Comment by Yong-Du** [comment]
Hi,

I get it now, thank you for the comment.

Best,
Yong
