### ISSUE TITLE
Problem with matching of C_qe from Warsaw to JMS basis

### ISSUE THREAD

**Issue by micha-a-schmidt** [wilson-eft/wilson#96]
There is a problem with the matching of the Wilson coefficient C_{qe}. When matching to weak effective theory, the mixing matrices for up and down-type quarks drop out, since 
(Qbar \gamma^\mu Q_L) (ebar \gamma_\mu e_R) = (ubar \gamma^\mu u_L) (ebar \gamma_\mu e_R) + (dbar \gamma^\mu d_L) (ebar \gamma_\mu e_R) , but there are off-diagonal entries in the result of Wilson. See [Matching_Cqe_Warsaw_JMS.pdf](https://github.com/wilson-eft/wilson/files/8753717/Matching_Cqe_Warsaw_JMS.pdf) for a simple example. 

Starting with (q_2 q_2) with WC = 1, the (u_1 u_1) operator is generated with a coefficient ~ V_{us} V^*_{us} ~ 0.05.
Similarly for (q_3 q_3), Wilson returns  (u_1 u_1) ~ V_{ub} V^*_{ub} ~ 1.3e-5, and (u_2 u_2) ~ V_{cb} V^*_{cb} ~ 1.7e-3.

**Comment by DavidMStraub** [comment]
Can you try with `Warsaw up` as input basis?

**Comment by micha-a-schmidt** [comment]
Thanks for the quick reply! 
There are also off-diagonal entries. This time for down-type quarks.
[Matching_Cqe_Warsaw_up_JMS.pdf](https://github.com/wilson-eft/wilson/files/8753880/Matching_Cqe_Warsaw_up_JMS.pdf).

**Comment by micha-a-schmidt** [comment]
The result in Wilson is correct. The CKM matrix only drops out if the SMEFT Wilson coefficient is proportional to the identity in the quark flavours.
