### ISSUE TITLE
Upload of wilson v2.3 to PyPI

### ISSUE THREAD

**Issue by peterstangl** [wilson-eft/wilson#98]
@jasonaebischerGIT  @dvandyk @klieret @DavidMStraub I just released wilson v2.3 but the upload to PyPI didn't work and I realized that only you are PyPI maintainers of wilson. It would be nice if one of you could upload the latest release to PyPI.

**Comment by DavidMStraub** [comment]
Hi, why did the workflow fail?

**Comment by peterstangl** [comment]
I thought it didn't work since I'm not a maintainer on PyPI, but actually it seems that the workflow was not triggered at all by the new release and I don't know why.

**Comment by DavidMStraub** [comment]
Looking into it. It did run but this IF
https://github.com/wilson-eft/wilson/blob/master/.github/workflows/check%2Bdeploy.yaml#L72
evaluated to false. Offending line added by @dvandyk  in https://github.com/wilson-eft/wilson/commit/3660307a5db98a5ba39fad9bf04080d7c3462fcb.

**Comment by DavidMStraub** [comment]
Uploaded to PyPI, but the workflow should be fixed.

**Comment by peterstangl** [comment]
> Looking into it. It did run but this IF https://github.com/wilson-eft/wilson/blob/master/.github/workflows/check%2Bdeploy.yaml#L72 evaluated to false. Offending line added by @dvandyk in [3660307](https://github.com/wilson-eft/wilson/commit/3660307a5db98a5ba39fad9bf04080d7c3462fcb).

Where do see this? I don't see any workflow run for the release at all. The last workflow run I see is from the commit that changed the version number and there this IF in https://github.com/wilson-eft/wilson/blob/master/.github/workflows/check%2Bdeploy.yaml#L72 evaluates to false since it was a commit and not a release that has triggered the event. Were you looking at that one?

**Comment by dvandyk** [comment]
> Looking into it. It did run but this IF https://github.com/wilson-eft/wilson/blob/master/.github/workflows/check%2Bdeploy.yaml#L72 evaluated to false. Offending line added by @dvandyk in [3660307](https://github.com/wilson-eft/wilson/commit/3660307a5db98a5ba39fad9bf04080d7c3462fcb).

Hi @DavidMStraub, this line is correct, since it prohibits deployment on all events except a ``release`` event.
@peterstangl is right, there should be another workflow appear in the list, triggered by a ``release`` event. Looking into it.

**Comment by dvandyk** [comment]
And here we go... I used the wrong event type:
```
Note: Workflows are not triggered for the created, edited, or deleted activity types
for draft releases. When you create your release through the GitHub browser UI,
your release may automatically be saved as a draft.
```
Here https://github.com/wilson-eft/wilson/blob/bf8cf0d43b7023ff87649eb2d50245b0106b8847/.github/workflows/check%2Bdeploy.yaml#L8
it should read ``[published]``.

**Comment by peterstangl** [comment]
@dvandyk indeed, I first drafted the release before publishing it. So I actually never "created" it and thus the workflow was not triggered.

**Comment by dvandyk** [comment]
PR #99 should fix this issue, and another that I noticed while reading the Github Actions documentation.

**Comment by peterstangl** [comment]
Fixed by @DavidMStraub uploading the release and @dvandyk fixing the workflow in #99.
